# Generated by Django 4.1.7 on 2023-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "CRN",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("StartTime", models.CharField(max_length=10)),
                ("EndTime", models.CharField(max_length=10)),
                ("Days", models.CharField(max_length=10)),
                ("Building", models.CharField(max_length=30)),
                ("Room", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ClassQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CRN", models.IntegerField()),
                ("StartTime", models.TimeField(blank=True, null=True)),
                ("EndTime", models.TimeField(blank=True, null=True)),
                ("Days", models.CharField(blank=True, max_length=10, null=True)),
                ("Building", models.CharField(blank=True, max_length=30, null=True)),
                ("Room", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
