# Generated by Django 4.1.7 on 2023-03-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                ("SubjectCode", models.CharField(max_length=10)),
                ("CourseNumber", models.CharField(max_length=5)),
                (
                    "CRN",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("StartTime", models.CharField(max_length=10)),
                ("EndTime", models.CharField(max_length=10)),
                ("Days", models.CharField(max_length=10)),
                ("Building", models.CharField(max_length=30)),
                ("Room", models.CharField(max_length=10)),
            ],
        ),
    ]
