# Generated by Django 4.1.7 on 2023-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('CRN', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('Section', models.CharField(max_length=10)),
                ('Time', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
    ]
