# Generated by Django 4.1.7 on 2023-04-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classinfo",
            name="Building",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="CRN",
            field=models.CharField(
                blank=True, max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="CourseNumber",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="Days",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="EndTime",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="Room",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="StartTime",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="classinfo",
            name="SubjectCode",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
