# Generated by Django 4.1.7 on 2023-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classquery",
            name="CRN",
            field=models.IntegerField(
                blank=True, help_text="5-digit class code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="classquery",
            name="Days",
            field=models.CharField(
                blank=True, help_text="In the form of TR", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="classquery",
            name="EndTime",
            field=models.TimeField(
                blank=True, help_text="In the form of 04:00PM", null=True
            ),
        ),
        migrations.AlterField(
            model_name="classquery",
            name="StartTime",
            field=models.TimeField(
                blank=True, help_text="In the form of 09:00AM", null=True
            ),
        ),
    ]
