# Generated by Django 4.1.7 on 2023-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinfo',
            old_name='Location',
            new_name='Building',
        ),
        migrations.RenameField(
            model_name='classinfo',
            old_name='Day',
            new_name='Days',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='CourseNumber',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='Type',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='EndTime',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinfo',
            name='Room',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinfo',
            name='StartTime',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
