# Generated by Django 4.1.7 on 2023-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0002_rename_location_classinfo_building_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CRN", models.IntegerField()),
                ("StartTime", models.CharField(blank=True, max_length=10, null=True)),
                ("EndTime", models.CharField(blank=True, max_length=10, null=True)),
                ("Room", models.CharField(blank=True, max_length=10, null=True)),
                ("Building", models.CharField(blank=True, max_length=30, null=True)),
                ("Days", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
