# Generated by Django 4.1.7 on 2023-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0002_alter_classquery_crn_alter_classquery_days_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ClassQuery",),
    ]
