# Generated by Django 4.1.7 on 2023-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0003_classquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classinfo", name="EndTime", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="classinfo", name="StartTime", field=models.TimeField(),
        ),
    ]
