# Generated by Django 4.1.7 on 2023-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0004_alter_classinfo_endtime_alter_classinfo_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classquery",
            name="EndTime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="classquery",
            name="StartTime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
