# Generated by Django 4.1.7 on 2023-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraperapp", "0005_alter_classquery_endtime_alter_classquery_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classinfo", name="CRN", field=models.CharField(max_length=10),
        ),
    ]
